# -*- coding: utf-8 -*-
"""first_colab.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1ql5MztD_JjZeeBi05d2JpebL9S8QRdhh
"""

print("Hello Word!")

a =3
b = 4
print(a + b )



"""**Python**で*人工知能*のコードを書いていきましょう。  
Colabにはコードセルとテキストセルがあります。

1.   リスト項目
2.   リスト項目
3.番号付きの箇条書きです



*   リスト項目
*   リスト項目
*　箇条書きです

[Google検索](https://google.com)

#みんなのAI講座
## みんなの日本語
### みんなのニュース

$$ y = 2x + 1 $$
"""